version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "5959:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: "supermarket"
      MYSQL_USER: "sa"
      MYSQL_PASSWORD: ""
    volumes:
      - ./data:/var/lib/mysql
